spring:
  application:
    name: webflux

  r2dbc:
    url: r2dbc:mysql://localhost:3306/webflux
    username: root
    password: 1234

  liquibase:
    enabled: false
  flyway:
    enabled: false

logging:
  level:
    org.springframework.r2dbc.core: debug
